from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import numpy as np
from timelines.models import PostModel

# Tuning constants
SIMILARITY_THRESHOLD = 0.30   # Minimum cosine similarity (0–1) to surface a result
MAX_RESULTS = 10               # Cap displayed results

_model = None  # Lazy-loaded on first search request, not at server startup


def _get_model():
    global _model
    if _model is None:
        # pyrefly: ignore [missing-import]
        from sentence_transformers import SentenceTransformer
        _model = SentenceTransformer('all-MiniLM-L6-v2')
    return _model


def s_v(request):
    return render(request, 'ai_search/results.html')


@login_required(login_url='/')
def ai_search_view(request):
    query = request.GET.get('q', '').strip()
    results = []
    warning = None

    if query:
        # ------------------------------------------------------------------
        # Optimized path: load pre-computed embeddings from the database.
        # Embeddings are generated by timelines.signals on post save, so this
        # query does zero ML inference on posts — it's a plain DB read.
        # Only the short query string is encoded at search time.
        # ------------------------------------------------------------------
        posts_with_embeddings = PostModel.objects.exclude(
            embedding__isnull=True
        ).exclude(content='')

        if not posts_with_embeddings.exists():
            warning = "No indexed posts yet. Posts will become searchable after being created."
        else:
            from sklearn.metrics.pairwise import cosine_similarity

            posts = list(posts_with_embeddings)
            stored_embeddings = np.array([p.embedding for p in posts], dtype=np.float32)

            # Encode only the short query — O(1), not O(n posts)
            model = _get_model()
            query_embedding = model.encode([query], convert_to_numpy=True)

            similarities = cosine_similarity(query_embedding, stored_embeddings)[0]

            # Filter by threshold, sort descending, convert to percentage
            scored = [
                (post, round(float(sim) * 100, 1))
                for post, sim in zip(posts, similarities)
                if sim >= SIMILARITY_THRESHOLD
            ]
            scored.sort(key=lambda x: x[1], reverse=True)
            results = scored[:MAX_RESULTS]

    return render(request, 'ai_search/results.html', {
        'results': results,
        'query': query,
        'warning': warning,
    })