# Generated by Django 5.2.1 on 2025-06-07 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="embedding",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None
            ),
        ),
    ]
